// Generates examples/output.rs with a Vec<GarbledInstance> for seeds 0..=3.
// Usage:
//   RUST_LOG=info cargo run --example groth16_build_output --release
// The generated file contains valid Rust code you can `include!()` and use
// as a fixed mock dataset.

use std::{fs::File, io::Write as _};

use garbled_snark_verifier::{
    AESAccumulatingHash, AesNiHasher, GarbledWire,
    circuit::{CircuitBuilder, StreamingResult, modes::GarbleMode},
    garbled_groth16,
};
use rayon::prelude::*;
use tracing::info;

const CAPACITY: usize = 150_000;

fn fmt_bytes(bytes: &[u8; 16]) -> String {
    let mut out = String::with_capacity(16 * 6);
    out.push('[');
    for (i, b) in bytes.iter().enumerate() {
        if i != 0 {
            out.push_str(", ");
        }
        let _ = std::fmt::Write::write_fmt(&mut out, format_args!("0x{:02x}", b));
    }
    out.push(']');
    out
}

fn fmt_s(s: garbled_snark_verifier::S) -> String {
    // Emit S from its numeric value (decimal u128)
    let v = s.to_u128();
    format!("garbled_snark_verifier::S::from_u128({})", v)
}

fn fmt_wire(w: &GarbledWire) -> String {
    format!(
        "garbled_snark_verifier::GarbledWire {{ label0: {}, label1: {} }}",
        fmt_s(w.label0),
        fmt_s(w.label1),
    )
}

fn main() {
    garbled_snark_verifier::init_tracing();

    let inputs = garbled_groth16::GarblerInput {
        public_params_len: 0,
        vk: garbled_snark_verifier::test_utils::dummy_vk(),
    };

    info!("Garbling seeds 0..=3 (in parallel) and emitting examples/output.rs...");

    // Parallel garbling for seeds 0..=3 using rayon
    let seeds: Vec<u64> = (0u64..=3u64).collect();
    let mut instances: Vec<(u64, garbled_snark_verifier::cut_and_choose::GarbledInstance)> = seeds
        .par_iter()
        .map(|&seed| {
            info!("garbling_seed" = seed);
            let res: StreamingResult<GarbleMode<AesNiHasher, AESAccumulatingHash>, _, GarbledWire> =
                CircuitBuilder::streaming_garbling(
                    inputs.clone(),
                    CAPACITY,
                    seed,
                    AESAccumulatingHash::default(),
                    garbled_groth16::verify,
                );
            let instance: garbled_snark_verifier::cut_and_choose::GarbledInstance = res.into();
            (seed, instance)
        })
        .collect();

    // Ensure deterministic order in the generated file
    instances.sort_by_key(|(seed, _)| *seed);

    // Build the Rust file content
    let mut file_text = String::new();
    file_text.push_str("// Auto-generated by examples/groth16_build_output.rs\n");
    file_text.push_str("// Do not edit manually. Regenerate via: \n");
    file_text.push_str("//   cargo run --example groth16_build_output --release\n\n");
    file_text.push_str("use garbled_snark_verifier::{S, GarbledWire};\n");
    file_text.push_str("use garbled_snark_verifier::cut_and_choose::GarbledInstance;\n\n");
    file_text.push_str("pub fn mock_garbled_instances() -> Vec<GarbledInstance> {\n");
    file_text.push_str("    vec![\n");

    for (_seed, instance) in instances.into_iter() {
        // Emit struct literal
        file_text.push_str("        GarbledInstance {\n");
        file_text.push_str(&format!(
            "            false_wire_constant: {},\n",
            fmt_wire(&instance.false_wire_constant)
        ));
        file_text.push_str(&format!(
            "            true_wire_constant: {},\n",
            fmt_wire(&instance.true_wire_constant)
        ));
        file_text.push_str(&format!(
            "            output_wire_values: {},\n",
            fmt_wire(&instance.output_wire_values)
        ));

        // input wires
        file_text.push_str("            input_wire_values: vec![\n");
        for w in &instance.input_wire_values {
            file_text.push_str("                ");
            file_text.push_str(&fmt_wire(w));
            file_text.push_str(",\n");
        }
        file_text.push_str("            ],\n");

        // ciphertext hash result
        file_text.push_str(&format!(
            "            ciphertext_handler_result: {},\n",
            fmt_bytes(&instance.ciphertext_handler_result)
        ));

        file_text.push_str("        },\n");
    }

    file_text.push_str("    ]\n");
    file_text.push_str("}\n");

    let mut f = File::create("examples/output.rs").expect("open output.rs for write");
    f.write_all(file_text.as_bytes()).expect("write output.rs");
    f.flush().ok();

    info!("Wrote examples/output.rs (mock_garbled_instances)");
}
