//! Generates examples/soldering_output.rs with a real SolderingProof.
//! Uses test_only mocked garbled instances but generates a real SP1 soldering proof.
//! Usage:
//!   RUST_LOG=info cargo run --example groth16_build_soldering_proof --release --features sp1-soldering,test-utils
//! The generated file contains valid Rust code you can `include!()` and use
//! as a fixed mock soldering proof.

use std::{fs::File, io::Write as _};

use garbled_snark_verifier::{
    S, groth16_cut_and_choose as ccn, hashers::Sha256LabelCommitHasher as ExampleHasher,
};
use tracing::info;

fn fmt_string_array(arr: &[String]) -> String {
    let mut out = String::new();
    out.push_str("[\n");
    for s in arr {
        out.push_str(&format!("                \"{}\".to_owned(),\n", s));
    }
    out.push_str("            ]");
    out
}

fn fmt_bytes(bytes: &[u8]) -> String {
    let mut out = String::new();
    out.push('[');
    for (i, b) in bytes.iter().enumerate() {
        if i != 0 {
            if i % 8 == 0 {
                out.push_str(",\n                ");
            } else {
                out.push_str(", ");
            }
        }
        out.push_str(&format!("{}", b));
    }
    out.push(']');
    out
}

fn fmt_deltas(deltas: &[Vec<(u128, u128)>]) -> String {
    let mut out = String::new();
    out.push_str("vec![\n");
    for delta_vec in deltas {
        out.push_str("            vec![\n");
        for &(a, b) in delta_vec {
            out.push_str(&format!("                ({}, {}),\n", a, b));
        }
        out.push_str("            ],\n");
    }
    out.push_str("        ]");
    out
}

fn main() {
    garbled_snark_verifier::init_tracing();

    if !garbled_snark_verifier::hardware_aes_available() {
        eprintln!(
            "Warning: AES hardware acceleration not detected; using software AES (not constant-time)."
        );
    }

    info!("Setting up cut-and-choose with mock config");
    let cfg = ccn::mock_config();

    info!("Creating Garbler with test_only mocked instances");
    let mut g = ccn::Garbler::create_test_only(cfg.clone());

    info!("Step 1.2 — Commit phase one (mocked)");
    let _commit1 = g.commit_phase_one::<ExampleHasher>();

    info!("Step 1.4 — Commit phase two with fixed nonce");
    let nonce = S::from_u128(0);
    let _commit2 = g.commit_phase_two::<ExampleHasher>(nonce);

    // With 4 total instances (0, 1, 2, 3) and 2 to finalize, we pick [2, 3]
    let finalize_indexes =
        ccn::Evaluator::create_test_only(cfg, g.commit_phase_one::<ExampleHasher>())
            .finalized_indexes()
            .to_vec();

    info!("Step 2 — Open commit with finalize indexes [{finalize_indexes:?}]");
    let _open_commit = g.open_commit_without_ciphertexts(finalize_indexes);

    info!("Step 4 — Generating REAL soldering proof (this may take a while)...");
    let proof = g.do_soldering();

    info!("Formatting proof into Rust source code");
    let mut file_text = String::new();
    file_text.push_str("// Auto-generated by examples/groth16_build_soldering_proof.rs\n");
    file_text.push_str("// Do not edit manually. Regenerate via:\n");
    file_text.push_str("//   cargo run --example groth16_build_soldering_proof --release --features sp1-soldering\n\n");
    file_text.push_str("use garbled_snark_verifier::sp1_soldering::SolderingProof;\n\n");
    file_text.push_str("pub fn mock_soldering_proof() -> SolderingProof {\n");
    file_text.push_str("    SolderingProof {\n");
    file_text.push_str("        proof: sp1_prover::Groth16Bn254Proof {\n");
    file_text.push_str(&format!(
        "            public_inputs: {},\n",
        fmt_string_array(&proof.proof.public_inputs)
    ));
    file_text.push_str(&format!(
        "            encoded_proof: \"{}\".to_owned(),\n",
        proof.proof.encoded_proof
    ));
    file_text.push_str(&format!(
        "            raw_proof: \"{}\".to_owned(),\n",
        proof.proof.raw_proof
    ));
    file_text.push_str(&format!(
        "            groth16_vkey_hash: {},\n",
        fmt_bytes(&proof.proof.groth16_vkey_hash)
    ));
    file_text.push_str("        },\n");
    file_text.push_str(&format!("        deltas: {},\n", fmt_deltas(&proof.deltas)));
    file_text.push_str("    }\n");
    file_text.push_str("}\n");

    let mut f = File::create("examples/soldering_output.rs").expect("create soldering_output.rs");
    f.write_all(file_text.as_bytes())
        .expect("write soldering_output.rs");
    f.flush().ok();

    info!("Successfully wrote examples/soldering_output.rs");
}
